name: Run With Java 8

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '8'
        cache: maven
    
    - name: Display Java version
      run: java -version
    
    - name: Build and install cloudsim module
      run: |
        cd modules/cloudsim
        mvn clean install -DskipTests
    
    - name: Build cloudsim-examples module
      run: |
        cd modules/cloudsim-examples
        mvn clean package
    
    - name: Run AutoScalingExample
      run: |
        cd modules/cloudsim-examples
        mvn exec:java -Dexec.mainClass="org.cloudbus.cloudsim.examples.AutoScalingExample" -Dexec.cleanupDaemonThreads=false
    
    - name: Package with dependencies
      run: |
        cd modules/cloudsim-examples
        mvn assembly:single -DdescriptorId=jar-with-dependencies
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: cloudsim-jars
        path: |
          modules/cloudsim/target/*.jar
          modules/cloudsim-examples/target/*.jar 